name: ZORO UI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify a Node.js version

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove node_modules
        run: |
          rm -rf node_modules

      - name: Install dependencies
        run: |
          npm i
          npm update jest typescript  # Update Jest and TypeScript
          npm install ts-node ts-jest --save-dev # Install ts-node and ts-jest

      - name: Run unit tests
        env:
          TS_NODE_TRANSPILE_ONLY: "true"
        run: npx jest --verbose # Run Jest with verbose output

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run Cypress tests
        run: npx cypress run
